### ISSUE TITLE
Status stuck at Installing

### ISSUE THREAD

**Issue by jurajcik** [tuwiendsg/SALSA#33]
May be related to the issue #32 . I have successfully run the deployment script of the software node manually, but when submitting the tosca, SALSA stuck at the sate INSTALLING. Please, let me know if this is a bug or there is a fault in the input.

http://128.130.172.215/salsa/upload/files/juraj/issues/mela_tosca.xml

**Comment by leduchung** [comment]
this is caused by the wget command in the installation script. The command show a status bar that produce a lot of output and overflow the java buffer. This only happen when downloading large files. For quick overpass the stuck, using "wget -q" (silent wget). 

Otherwise, SALSA now understands the "misc" artifact type, that download additional files and archives to support the deployment. This enable to remove "fixed links" in the script and move them to the description (TOSCA).
